### ISSUE TITLE
conda-unpack-script.py line 226 and line 66

### ISSUE THREAD

**Issue by 51M0N3-3XC** [Sanster/iopaint-docs#33]
overall the application 1clickinstall that I purchased months ago has never worked well;

for example every time I start win_config.bat:

Traceback (most recent call last): File "C:\IOPaint-v1\installer\Scripts\conda-unpack-script.py", line 226, in <module> update_prefix(os.path.join(new_prefix, path), new_prefix,
File "C:\IOPaint-v1\installer\Scripts\conda-unpack-script.py", line 66, in update_prefix with open(path, 'rb+') as fh:
PermissionError: [Errno 13] Permission denied: 'C:\\IOPaint-v1\\installer\\DLLs/_tkinter.pyd'

or other times:

Traceback (most recent call last): File "C:\IOPaint-v1\installer\Scripts\conda-unpack-script.py", line 226, in <module>
update_prefix(os.path.join(new_prefix, path), new_prefix,
File "C:\IOPaint-v1\installer\Scripts\conda-unpack-script.py", line 66, in update_prefix
with open(path, 'rb+') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\IOPaint-v1\\installer\\Library/lib/tdbc1.1.3/tdbcConfig.sh'Channels:

then it starts but sometimes it doesn't save the configuration correctly and, when it happens, it completely ruins the installation.

I tried download the 1clickinstall application again hoping that it had been fixed but apparently it hasn't been...

I ask that it be fixed (even more so because it is paid) and that adequate support be given
Thanks

**Comment by Sanster** [comment]
I split the old win_config.bat file.

- [win_setup.bat](https://github.com/Sanster/IOPaint/blob/main/scripts/user_scripts/win_setup.bat): Used for installing dependencies for the first time
- [win_config.bat](https://github.com/Sanster/IOPaint/blob/main/scripts/user_scripts/win_config.bat): Launches the gradio parameter configuration interface
- [win_update.bat](https://github.com/Sanster/IOPaint/blob/main/scripts/user_scripts/win_update.bat): To be executed when you need to update the iopaint version

Please unzip the original zip again and download the three bat files mentioned above.
